wordpress:
  build: .
  tty: true
  links:
    - database
  ports:
    - "80:80"

database:
  image: mysql
  ports:
    - "3306:3306"
  volumes:
    - ./database:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: example
    MYSQL_DATABASE: wordpress
    MYSQL_USER: admin
    MYSQL_PASSWORD: "123456"

