confluence:
  build: .
  ports:
    - "9090:9090"
  volumes:
    - home:/opt/confluence-home
  links:
    - database

database:
  image: postgres:9.4
  environment:
    - POSTGRES_DB=db_name
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
  volumes:
    - pg-data:/var/lib/postgresql/data  
