bamboo:
  build: .
  ports:
    - "8085:8085"
  volumes:
    - /opt/atlassian/application-data/bamboo-home:/opt/atlassian/application-data/bamboo-home
  links:
    - database

database:
  image: postgres:9.4
  environment:
    - POSTGRES_DB=yourdb
    - POSTGRES_USER=yourdbuser
    - POSTGRES_PASSWORD=yourpass
  volumes:
    - ./data:/var/lib/postgresql/data
